// Keyboard keys values
#define LEFT_CTRL 340

// Spritefont values
#define FONT_SPACING 1

// Array max index
#define MAX_LEVELS 10
#define MAX_BULLETS 10
#define MAX_FLOOR 300
#define MAX_ENEMIES 6
#define MAX_COINS 10

// Sprite sheet values
#define MAX_DECORATION 7
#define MAX_CLOUDS 8

#define LEVELIMAGE_WIDTH 141
#define LEVELIMAGE_HEIGHT 14

#define ENVIRONMENTIMAGE_WIDTH 152
#define ENVIRONMENTIMAGE_HEIGHT 73

#define ENVIRONMENTIMAGE_WIDTH 152
#define ENVIRONMENTIMAGE_HEIGHT 73

#define CASTLEIMAGE_WIDTH 198
#define CASTLEIMAGE_HEIGHT 176

#define MARIOIMAGE_WIDTH 180
#define MARIOIMAGE_HEIGHT 50

#define MAX_OFFSET 50
#define PIXEL_UNIT 30

#define MARIO_WIDTH 18
#define MARIO_HEIGHT 30

#define ENEMY_WIDTH 16
#define ENEMY_HEIGHT 16

#define FLOOR_OFFSETX 52
#define FLOOR_OFFSETY 30
#define FLOOR_WIDTH 16
#define FLOOR_HEIGHT 16

#define FIREBALL_OFFSETX 70
#define FIREBALL_OFFSETY 33
#define FIREBALL_WIDTH 8
#define FIREBALL_HEIGHT 8

#define COIN_OFFSETX 81
#define COIN_OFFSETY 34
#define COIN_WIDTH 8
#define COIN_HEIGHT 14

#define CLOUD_OFFSETX 59
#define CLOUD_OFFSETY 23
#define CLOUD_WIDTH 64 
#define CLOUD_HEIGHT 24

#define FLAG_OFFSETX 162
#define FLAG_OFFSETY 8
#define FLAG_WIDTH 16
#define FLAG_HEIGHT 170

#define PRINCESS_OFFSETX 131
#define PRINCESS_OFFSETY 24
#define PRINCESS_WIDTH 14
#define PRINCESS_HEIGHT 23
